# Generated by Django 4.0.2 on 2022-02-24 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='refresh_token',
        ),
        migrations.RemoveField(
            model_name='spotifytoken',
            name='user',
        ),
    ]
