# Generated by Django 4.0.2 on 2022-02-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_spotifytoken_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifytoken',
            name='expires_in',
        ),
    ]
