# Generated by Django 4.0.2 on 2022-02-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_remove_spotifytoken_expires_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotifytoken',
            name='expires_in',
            field=models.IntegerField(default=0),
        ),
    ]
